### ISSUE TITLE
derp

### ISSUE THREAD

**Issue by gerb82** [reteo/Survival-Industry#1]
forge version mismatches the required version, probably lite-loader crashes it.
will fix in 1.1.3

required forge version: 10.13.4.1492

**Comment by reteo** [comment]
Strange... I launched the game just fine.

**Comment by gerb82** [comment]
latest version?

**Comment by reteo** [comment]
1.1.2.  Yup.  Even placed a glass ceiling for my greenhouse.

**Comment by gerb82** [comment]
well, launcher version?

**Comment by reteo** [comment]
Launcher 1.4.8

**Comment by gerb82** [comment]
ok. probably the windows doesn't work with this then

**Comment by reteo** [comment]
My suggestion, clear out the launcher's instance of Survival Industry, and re-download it completely fresh.  In the meantime, I have classes to go to, so good luck!

**Comment by gerb82** [comment]
well, turns out my launcher was bugged as heck.
