### ISSUE TITLE
Signalum Can't Be Made

### ISSUE THREAD

**Issue by reteo** [reteo/Survival-Industry#10]
From the forum:
"Signalum can't be made. There's two different names for redstone in the smeltery, destabilized redstone and liquid redstone. Signalum's alloy recipe calls for the former, but only the latter can be made. NEI claims the painted ExtraUtilities versions of redstone blocks would melt into destabilized redstone, but it gets 'translated' into the normal liquid redstone instead."

**Comment by reteo** [comment]
The destabilized redstone cannot be made in the smelter, this is true.  However, putting redstone in the RoC rock melter will work.  Then, once you have enough destabilized redstone, simply pipe it to the smelter to combine with copper and silver for signalum.

**Comment by Cairon189** [comment]
You can make destabilized redstone in the smeltery, but lava is not hot enough to melt the redstone.  If you look at the recipe in NEI it says it needs 3000 degree fuel.  You need to fill the lava tank with blazing pyrotheum instead.  Pop in your regular redstone dust or blocks and you've got yourself some destabilized redstone.

**Comment by reteo** [comment]
Before long, this issue will no longer be relevant; Thermal Foundation will be removed from the pack at the same time Tinker's Construct is removed.  In its place will be added Metallurgy, which will cover the alloying process, and replace the missing copper and bronze equipment, as well as other alloys, such as electrum.
