### ISSUE TITLE
Adding Chromaticraft as an optional mod causes a crash on startup

### ISSUE THREAD

**Issue by artaficialAI** [reteo/Survival-Industry#102]
http://pastebin.com/EG85D67P
The above is a crash report
I have encountered this problem before with chromaticraft on my own, it is caused by either a version of the mod being out of date or newer than the other Rekia's mods. (I think)

**Comment by SvenKayser** [comment]
Please include a complete log (from logs/fml-client-latest.log) if possible.

**Comment by reteo** [comment]
Better yet, try this:  Try running the game again.  Once it crashes, you'll see a button on the ATLauncher log window labeled "Upload Log".  Click this, and then, when it says the log is uploaded, add a comment to this report, and paste.  It will automatically paste a link to the full log.

**Comment by reteo** [comment]
I just finished installing all the mods listed in the above log.  The problem was the "ChromatiCraft/AE2" bug.  I fixed the configuration so that the game will load.  Update and try again.

**Comment by artaficialAI** [comment]
Cool, I'll try it when I get home.
