### ISSUE TITLE
Lycanite Mobs Not Spawning

### ISSUE THREAD

**Issue by reteo** [reteo/Survival-Industry#105]
Report from Knuk (on Reddit):
"Hello, small problem I've been having with 1.6.0: I've enabled Lycanite Mobs in the optional hardcore mods, but I can't find any in my world. When the special events from that mod occur, nothing actually happens. Like, it will scream "poop party!" and then nothing else."

**Comment by reteo** [comment]
Okay, before I can help, I am going to need you to do this:

1. Go to the "Instances" tab in ATLauncher.
2. Right-click on the "Survival Industry" logo for the instance with the issue.
3. Click on "Share code"
4. Wait for "Share Code copied to the clipboard" to appear in the notification area.
5. Paste the share code into a reply in this issue thread.

I need this, so that I can test the issue using your exact game setup.

**Comment by samuellapointe** [comment]
Hey, thanks for this! The code is `6vr58lUv`

Some more info:

- I'm running a world generated using ATG, but it also did the same thing RTG. I tried vanilla generation a little bit but not long enough for it to me conclusive.

- On creative mode, spawning mobs using the spawn eggs in the mod works fine, and the mobs act like they should

- Items from the mod can be found in dungeons in my world

On my side, I will try to reproduce the problem with the default config plus Lycanites only.

**Comment by samuellapointe** [comment]
Update: I tried using the default mods and enabling only Lycanites as an extra, and it works. I will try to figure out which mod makes it stop working.

**Comment by samuellapointe** [comment]
Enabling both Lycanite Mobs and Mo' Creatures makes the issue happen. However, simply removing Mo' creatures from the pack I use doesn't solve the issue, which means there is at least one other mod responsible for it. I'm trying to find it.

**Comment by reteo** [comment]
Actually, Mo'Creatures brings in the "Custom Mob Spawner" mod, which is not listed in the launcher.  To fix this, you'll have to clean-install the modpack.  I'll fix things in ATLauncher to prevent them from being installed together in the future.

**Comment by reteo** [comment]
Okay, so in about 10 minutes, you can reload ATLauncher, and enabling Lycanite's Mobs will disable Custom Mob Spawner (and by extension, Mo'Creatures).

**Comment by samuellapointe** [comment]
Alright, removing Mo' Creatures and CustomMobSpawner from my server makes Lycanite' mobs spawn now. Thanks!
