### ISSUE TITLE
Enchanting Plus inscriber

### ISSUE THREAD

**Issue by gallowglass** [reteo/Survival-Industry#113]
The Arcane Inscriber from Enchanting Plus is behaving very strangely.  I gather that it is supposed to allow one to convert enchanted books to scrolls which can then be learned and then those enchantments become available at the enchantment table.  That doesn't happen.  I can place an inscriber and place a book on it.  I can right click and hold on the inscriber and runes flow, much like when one holds a scroll.  Eventually the book disappears, but the enchantment isn't appearing in the choices at the enchanting table.

Also, the inscriber is destroyed when you punch it.

**Comment by reteo** [comment]
I'll have to look into this; it look like the bug was fixed for 1.10, but I don't know if they will backport the fix to 1.7.10.

**Comment by reteo** [comment]
Looks like there's not much that can be done about the breakable block (Darkhax-Minecraft/Enchanting-Plus#35).  However, I tested the arcane inscriber, and it looks like it's working.  Once the enchantment book disappears from the inscriber, a scroll appears in my hand (when I'm in survival mode).

What enchantment were you trying to learn, and did a scroll appear in your inventory after finishing the book?

**Comment by gallowglass** [comment]
I just tried this again and it worked.  I must have been doing something wrong before.  Sorry for bugging you.
