### ISSUE TITLE
Game wont start

### ISSUE THREAD

**Issue by thebalck** [reteo/Survival-Industry#116]
My game isnt starting, no errors in console
`If i do the share code this is the only thing i get in the paste

i1DPVs6a

**Comment by reteo** [comment]
That's fine; that's the share code.  Using that code while installing an instance of Survival Industry will automatically check everything that you originally had checked.  That way, I can test the game using the exact same mods you chose when setting it up.

**Comment by thebalck** [comment]
Hello thanks for your time ive already figure the problem out, it was the latest nvidia driver justr a fast downgrade and its all good

**Comment by reteo** [comment]
What was the version of the new driver?  I might want to test it in the future.

**Comment by thebalck** [comment]
376.33-desktop-win10-64bit-international-whql.exe
This is the old one (the one that works)
The new one was the latest in nvidia site

**Comment by reteo** [comment]
Hmmm... that means... yes, Version 378.49

Okay, I'm going to leave this issue open for now, in case anyone else has the same issue.

**Comment by thebalck** [comment]
I was reading some stuff and that latest driver crashed lots of games not only minecraft

**Comment by reteo** [comment]
Sounds good.  Thanks for the information!
