### ISSUE TITLE
Redstone Pump crashes server

### ISSUE THREAD

**Issue by Cylkin** [reteo/Survival-Industry#118]
Just placing the expanded redstone pump and supplying a redstone signal crashes the server until deleted.
Tested with a clean install of 1.6.1 (share code p3cKsOQW).

**Comment by reteo** [comment]
First of all, that is a LOT of worldgen.  You muse be a VERY patient person.  Mad props.

Back to the issue at hand:  The crash seems to be something in Expanded Redstone; the issue has been reported, so now all we can do is wait.

ReikaKalseki/Reika_Mods_Issues#1408

**Comment by reteo** [comment]
The issue has been resolved on Reika's end.  However, it won't make it into this modpack until v17 of Reika's mods are released.

**Comment by reteo** [comment]
V17 of the mods have been released.  The pump is no longer crashing the game.
