### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by MoonlitCoder** [reteo/Survival-Industry#122]
So this seems to happen shortly (if not immediately) after what I'm guessing is a meteor impact. 

I hear a whoosh noise, and my system chugs, then I'm staring at my desktop.

Log: http://paste.atlauncher.com/view/d17a28e6

Share code: dZjuue9k

(I'm infinitehorizons on minecraftforums if you need to get ahold of me)

**Comment by reteo** [comment]
You pressed the "Upload Log" button _after_ the crash?

**Comment by MoonlitCoder** [comment]
My new instance had crashed. I reloaded it, and it crashed again.

This log file is from the reloaded instance (second crash, reinstalled
instance, same issue).

I've checked the saved logs, and do not have a log from either of the other
two crashes.

(These being: The instance I upgraded, and then had this issue. Or the
reinstalled version with a new instance and this issue.)

I'd likely closed the console window, unaware that it was required for
logging. I'd also not been expecting issues.

I'll see what else I can unearth, and if I can get it to repeat and
disgorge a proper stack dump this time.

-Sean

**Comment by MoonlitCoder** [comment]
(I hope this uploads properly)

[crash-2017-08-19_20.57.33-server.txt](https://github.com/reteo/Survival-Industry/files/1237761/crash-2017-08-19_20.57.33-server.txt)

**Comment by MoonlitCoder** [comment]
Crashed again, got a log this time:

(this was after loading the game, and getting the survival industry splash screen. 
I hit "Play Single Player" and chose my world)

http://paste.atlauncher.com/view/af5e3e99

**Comment by reteo** [comment]
Okay, I was able to replicate the problem.  Looks like a bug in Reika's mod.  I'll have to submit a bug report for now, and see if a workaround can be found, at least until a new version is released.

**Comment by reteo** [comment]
Well, it looks like the ball is in Reika's court now.  Once he updates MeteorCraft, things should go swimmingly.

**Comment by reteo** [comment]
Okay, the new MeteorCraft has been added to the modpack.  Give it some time (a half hour should do), and then update the modpack.

**Comment by MoonlitCoder** [comment]
Will do, I'll update and give it a whirl tonight.

Thank you!

Sean

On Aug 21, 2017 1:20 PM, "reteo" <notifications@github.com> wrote:

Okay, the new MeteorCraft has been added to the modpack. Give it some time
(a half hour should do), and then update the modpack.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/reteo/Survival-Industry/issues/122#issuecomment-323842680>,
or mute the thread

**Comment by MoonlitCoder** [comment]
Just found out about the command /meteor (heh), after 20-30 impacts I got an end stone meteor and no problems were to be had. 

I think you can mark this one completed. 

Thank you very much!

**Comment by reteo** [comment]
Good enough!
