### ISSUE TITLE
Tall grass not dropping seeds.

### ISSUE THREAD

**Issue by lemonbarking** [reteo/Survival-Industry#123]
Until you find a village you can't get vanilla wheat seeds. The bigger problem is that there doesn't seem to be any other way to get your first canola seeds for lubricant production. I saw that an early bee can get you some but you still need canola planted nearby for the bee to even begin working.

I've tried breaking grass by punching and using different tools to no avail.

Using most recent version of pack.

**Comment by reteo** [comment]
That's a feature of Hunger Overhaul.  To get seeds, you need to use the hoe on unwatered grass blocks.  They will turn to dirt blocks and have a chance of popping a number of different seed types.
