### ISSUE TITLE
1.7 Skyblock Balance: Clicker is gated behind centrifuge

### ISSUE THREAD

**Issue by artaficialAI** [reteo/Survival-Industry#145]
The Clicker is gated behind the RC centrifuge which means by the time you can get a clicker it won't be of any use.  I'm assuming the point of the clicker is to give early game sieving automation, but it can't be crafted until you can get nether quartz, which is gated behind the RC centrifuge.  If you already have a centrifuge you won't be using a sieve for materials, you'll be using the centrifuge.

**Comment by reteo** [comment]
Hmmm... lemme check my records; I could have sworn I reverted that setting...

**Comment by reteo** [comment]
Huh... apparently it didn't get saved.  I had removed the original chance of nether quartz, and replaced it with a 2% chance (to encourage moving up to the centrifuge).  During my failed attempts to apply a tooltip to the obsidian concrete, the changes must have been reverted.  I'm putting them back in now.

**Comment by reteo** [comment]
Okay, it should work now; just reinstall the modpack, and make sure to re-check "Skyblock Game"; a bug with ATLauncher keeps unchecking it.
