### ISSUE TITLE
1.6.5 Extrautilities causes crash only on dedicated server.

### ISSUE THREAD

**Issue by artaficialAI** [reteo/Survival-Industry#151]
https://pastebin.com/sB6x9FNL

Extra Utilities causes a crash on SI dedicated servers running pack version 1.6.5.
The crash occurs during the server's startup/load.

**Comment by artaficialAI** [comment]
Removing Extra utilities causes the server to load with no issues.

**Comment by artaficialAI** [comment]
Going into the ExtraUtilities.cfg and changing:  
 B:EnderQuarryEnabled=true    ---->    B:EnderQuarryEnabled=false  
fixes the issue.  The server starts with no issues.

**Comment by reteo** [comment]
I'll get to that as soon as I can.

**Comment by artaficialAI** [comment]
There is no option to install a dedicated server for 1.7 that I can see.

**Comment by reteo** [comment]
Odd... did you try "Create Server" and then select the correct version to install?

**Comment by artaficialAI** [comment]
Never mind, found it.  I just didn't see the 1.7 option.

**Comment by reteo** [comment]
Okay, I'll get that fixed.

**Comment by reteo** [comment]
Okay, it should be fixed.  Give it a few minutes, and then update.
