### ISSUE TITLE
TiCon Pick missing Mining XP

### ISSUE THREAD

**Issue by Rewyn** [reteo/Survival-Industry#17]
If you make a wooden pick with TiCon, it won't have mining XP to boost it's mining level. Even if you upgrade it's head to a better material.

**Comment by reteo** [comment]
The XP system is going to be going away in a future upgrade, since Tinker's Construct does not seem to be upgrading in 1.7.10 anymore.  I'm working on an alternate progression for early game.

**Comment by Rewyn** [comment]
Yea, just wanted it to be known.

**Comment by reteo** [comment]
Fair enough.   The replacement progression should be somewhat easier, putting the challenge more on finding the ore, where it really belongs.

**Comment by reteo** [comment]
issue resolved with 1.2.0
