### ISSUE TITLE
lava boats crashing

### ISSUE THREAD

**Issue by gerb82** [reteo/Survival-Industry#18]
trying to place the reinforced boat (or something named like that) crashed our test server.
more details when i get them

**Comment by reteo** [comment]
Does it happen in SSP?

**Comment by reteo** [comment]
Looks like we can replace Lava Boats with Better Boat.  We might also need to check out Small Boats to see about expanding our water-travel options.

**Comment by gerb82** [comment]
issue will get closed when 1.2.0 gets out.
lava boat was removed and replaced with small boats and better boat.

**Comment by reteo** [comment]
1.2.0 introduced better boats and small boats. Lava boats has been removed from the modpack.
