### ISSUE TITLE
somnia

### ISSUE THREAD

**Issue by gerb82** [reteo/Survival-Industry#2]
if we have somnia that is a client mod, does it work on servers?

**Comment by reteo** [comment]
I'm not sure; we will need to test that on a server.

**Comment by gerb82** [comment]
i am on it

**Comment by reteo** [comment]
Looking over the Somnia Mod thread indicates that Somnia does work in SMP; the tick rate is tied to the CPU, client in SSP, server in SMP.  I'm guessing it doesn't kick in until everyone goes to bed, same as vanilla server sleep mechanics.

**Comment by reteo** [comment]
Have you verified this?

**Comment by gerb82** [comment]
pretty much, testing again now

**Comment by reteo** [comment]
Nice. :)
