### ISSUE TITLE
Alloying using RoC Ore Flakes

### ISSUE THREAD

**Issue by reteo** [reteo/Survival-Industry#22]
Add recipes to create alloys (like bronze and electrum) using RotaryCraft's ore flakes in addition to the dusts from the Applied Energistics grindstone.

**Comment by reteo** [comment]
cannot alloy using or flakes but suggested a different form of alloying method to Reika.

**Comment by reteo** [comment]
In the next upcoming version of the modpack, Metallurgy will be added to supply the alloying mechanic for dusts, as well as a means of grinding dusts in an automatable way.

**Comment by jeffpengMC** [comment]
Has been resolved as stated above.
