### ISSUE TITLE
canola oil

### ISSUE THREAD

**Issue by gerb82** [reteo/Survival-Industry#24]
canola seeds will be added to the list of ingredients for cooking oil, and maybe also as a recipe in the presser (reteo will decide the second one)

**Comment by reteo** [comment]
MineTweaker does not seem to have support for Pam's Harvestcraft; if the oil recipe uses oredicts, then I might be able to oredict the seeds into an oil source, and *maybe* they'll work.

**Comment by gerb82** [comment]
it has an oredict
also modtweaker might support it, it's a minetweaker 3 addon

**Comment by reteo** [comment]
issue resolved with 1.2.0

**Comment by reteo** [comment]
Looks like MineTweaker keeps commenting out the oredict code for canola.
