### ISSUE TITLE
cobalt and ardite blocks

### ISSUE THREAD

**Issue by gerb82** [reteo/Survival-Industry#26]
from the forums:
"RotaryCraft version of Cobalt ingots cannot be crafted into a block like the normal TCon ones can, thus requiring re-melting them in the smeltery to convert and store them.
Ardite ingots are the same."

**Comment by reteo** [comment]
Recipes were added in MineTweaker; now both ingots can be used to make the blocks.

**Comment by reteo** [comment]
issue resolved with 1.2.0
