### ISSUE TITLE
Rice Plantability

### ISSUE THREAD

**Issue by MortisLegati** [reteo/Survival-Industry#29]
Pam's Harvestcraft Rice seeds can only be planted on Farmland, but will pop off.  The alternate methods of planting (water pad, water source block), do not allow either the seeds or the crop to be planted.

**Comment by reteo** [comment]
This is a mod interaction issue:
* MatrexsVigil/harvestcraft#14
* progwml6/HungerOverhaul#106

**Comment by reteo** [comment]
For now, the issue has been submitted, and I've added a workaround for the next version of Survival Industry.  You can download the updated config from [here](https://github.com/reteo/Survival-Industry/blob/master/config/HungerOverhaul/HungerOverhaul.cfg) if you want the changes immediately.  In this case, you should be able to plant the foods directly, meaning that while water-planting seeds won't work, water-planting the rice or cranberries should.

**Comment by reteo** [comment]
Changed the harvestcraft configuration again.  Planting has returned to seeds-only.  However, now all Pam's seeds should work in farmland.

**Comment by reteo** [comment]
In 1.4.0, rice should be plantable in farmland, either as a seed, or as the crop itself.  Additionally, the seed should work without issue using the AgriCraft crops.
