### ISSUE TITLE
Missing WAILA information for ReactorCraft Blocks (was: More WAILA issues)

### ISSUE THREAD

**Issue by Rewyn** [reteo/Survival-Industry#3]
WAILA doesn't show temperature and Tank1 (Hot co2) Carbon Dioxide Heat Exchanger.
Workaround by disabling WAILAPlugins.
ver 1.1.2

**Comment by reteo** [comment]
The issue has been submitted to Reika, who is working to resolve it.

**Comment by gerb82** [comment]
between, is there a way i could also manage tags and things so i can also close and open issues and things like that?

**Comment by reteo** [comment]
Hopefully, that should do it.

**Comment by reteo** [comment]
Let's keep this open until the issue is actually resolved. ;)

**Comment by reteo** [comment]
Issue resolved with 1.2.0

**Comment by reteo** [comment]
Issue resolved with 1.2.0.
