### ISSUE TITLE
Extractor Recipie

### ISSUE THREAD

**Issue by MortisLegati** [reteo/Survival-Industry#30]
The RotaryCraft worktable isn't recognising the extractor recipe.  It's also not just invisible, as clicking the output slot doesn't pick anything up.  Have used Oak and Spruce planks and the plank type doesn't appear to be an issue.
http://puu.sh/kKBNo/14e1e0d8d3.jpg

**Comment by reteo** [comment]
The stick at the bottom is a shaft unit, right?  Not an HSLA Steel Tool Rod?

**Comment by MortisLegati** [comment]
Yes, each item is the requested slot object from the recipe via NEI.  Is this not replicable?

**Comment by reteo** [comment]
I'm afraid not.

![Extractor Recipe](http://imgur.com/h5B8Oef)

**Comment by MortisLegati** [comment]
That's obviously what happened.  I don't know how I missed that, because I checked like five times.
