### ISSUE TITLE
InventoryTweaks crashes when trying to replace M&B BG slots

### ISSUE THREAD

**Issue by Rewyn** [reteo/Survival-Industry#32]
http://pastebin.com/6KzRChiG
http://openeye.openmods.info/crashes/f8d2be57af8179e403a6cb7636e07012
Happened in "Battlemode" (no clue how it's actually called), upon dropping a sword form the right hand.
Had a shield in the left hand as well.
Edit: Also happens if your left hand is empty.

**Comment by reteo** [comment]
I've encountered this as well. This seems to happen when inventory tweaks tries to replace a tool in the battle gear slots.

**Comment by reteo** [comment]
Issue already on kobata/inventory-tweaks#282

**Comment by reteo** [comment]
Inventory Tweaks auto-fill has been disabled.
