### ISSUE TITLE
RC Multiblock structures do not reinitialize client-side when logging on

### ISSUE THREAD

**Issue by ghost** [reteo/Survival-Industry#33]
When one re-enters the game after a log-out the RC multiblock structures coke oven and blast furnace to not reinitialize themselves client-side, so one needs to break and replace a block of it. It might be possible that other RC multiblock structures share the same issues.

It seems to be a synchronization issue. The same issue can be reproduced after spending some time in the nether. I do suspect it occurs every time a chunk gets unloaded and that this is isolated from other mods and solely a Railcraft problem.

Update: Having a local chunk loading event seems to resolve the issue.

**Comment by reteo** [comment]
Looks like this is a known issue with Railcraft multiblocks:  CovertJaguar/Railcraft#711

**Comment by reteo** [comment]
According to CovertJaguar, the issue seems to be solved; we'll close this for now.
