### ISSUE TITLE
Recipe ambiguity: BG2 Wooden Shield vs. RoC Wooden Gear

### ISSUE THREAD

**Issue by svenkayser** [reteo/Survival-Industry#34]

**Comment by reteo** [comment]
Odd... I had changed the center of the wooden shield to use a log instead of the planks used by the wooden gear.

**Comment by reteo** [comment]
I see what happened; the new recipe was added, but the old one wasn't removed.  Fixed with the next release.

**Comment by svenkayser** [comment]
It's fixed in the active source so I'm closing this.
