### ISSUE TITLE
Boring Machine cannot be enchanted

### ISSUE THREAD

**Issue by reteo** [reteo/Survival-Industry#36]
From "DriftinFool" on the [forum](http://forum.feed-the-beast.com/threads/1-7-10-survival-industry-rotarycraft-based-tech.112573/page-27#post-1497255):

"I can't seem to enchant the boring machine. Clicking on it with a book doesn't work like it has in the past. It works the way it should on the woodcutter, so I know I'm doing it right. I am able to enchant the borer using the "X" button in NEI to enchant it in cheat mode, so it seems to be enchantable. Although it doesn't work in enchanting tables(which it never did)."

**Comment by svenkayser** [comment]
I cannot confirm this at all. With the current build of SI it works just as intended.

**Comment by jeffpengMC** [comment]
After having run quite a few tests over the past days now I can confirm with certainty that this cannot be reproduced and most likely is an isolated bug on DriftinFool's end, possibly due some unknown mod interaction.
