### ISSUE TITLE
In-Building temperatures are acting strange

### ISSUE THREAD

**Issue by reteo** [reteo/Survival-Industry#37]
From "DriftinFool" on the [forum](http://forum.feed-the-beast.com/threads/1-7-10-survival-industry-rotarycraft-based-tech.112573/page-27#post-1497255):

"Not sure what mod it's related too, but the temperature inside buildings is acting strange. In my buildings that run east to west(longer in those directions), the west sides of the buildings have temperature drops that go from 25 degrees to -19 in the block next to it. It is not on a chunk border either, it is almost dead center of the chunk. I noticed because one set of my steam engines stopped working while another set that is 3 blocks east and 2 blocks south kept working. My fermenters that were on the floor above the steam engines also stopped working. But in my farming greenhouse that runs north to south(18x10), the west side of the building is maintaining proper indoor temps around 25, even against the west wall. So basically a rectangle building that runs east to west has outside temps on the west side while a rectangle building going north to south has consistent indoor temps in all areas. I thought maybe glass panes didn't count as sealing the building, so I swapped in full glass blocks but nothing changed. I also tried replacing carpenter's doors with vanilla doors and it didn't change anything either."

**Comment by reteo** [comment]
According to Reika, temperatures are statically linked to biome type, and biomes are not tied to chunk borders, so sometimes a biome change can happen in the middle of a chunk.  Check to see if the place where the temperature changes is also a place where the biome changes.

For clarification, the discussion regarding Reika's mods and temperature rules are in ReikaKalseki/Reika_Mods_Issues#377

**Comment by DriftinFool** [comment]
Then I am very confused as to what is going on. I placed the machines before Winter came and they worked fine. My steam engines ran long enough for me to grind an entire double iron chest of ores and my fermenters ran long enough to make a few stacks of ethanol crystals. Then a few MC days after the snow started and the ocean froze, my machines stopped working. My steam engines went from around 150 to 99 and turned off(using burning netherack for heat) and the fermenters dropped from around 23 down to -21. Basically the ambient temperatures dropped by around 50 degrees. All my temperature numbers are from Reika's machines according to Waila. 

I get some very huge fluctuations in temps within the same Biome. My base is spread over 3 biomes and here are the temp variances using a fermenter to get the temps.

Forest  I get -19, +14, and +25 all within 6 blocks with the -19 and +25 being side by side.
Beach -15 to +19 within 2 blocks
River -20 to +25 within 4 blocks

After some playing around, the mod that causes seasons changes the biome temperatures which makes RoC temperature sensitive machines stop working, while the mod that makes it stay warm in enclosed areas doesn't affect them. Unfortunately, there doesn't seem to be any consistency even within a biome. Kinda bummed cus all my steam engines and fermenters have stopped working.

**Comment by reteo** [comment]
At this point, I'm going to be disabling the seasons in HW, and waiting until v10 of Reika's mods to see if the issue is resolved; he indicated interest in mod compatibility between HW seasons and his mods, so things might stabilize when he does so.

**Comment by reteo** [comment]
The seasons have been re-enabled.  Reika has added support for seasons in v10 of RotaryCraft, so we'll consider this another incentive to get steel ready before winter, or wait until spring to begin the industrial stage of the game.  The temperatures should be more steady once 1.4.0 comes about.
