### ISSUE TITLE
read time out too fast

### ISSUE THREAD

**Issue by gerb82** [reteo/Survival-Industry#4]
well, tried to make a server with 2 friends, and one of them could not connect because when he connected it almost immediately kicked him saying read timed out.

**Comment by reteo** [comment]
Are there any logs that can be attached?

**Comment by gerb82** [comment]
http://pastebin.com/cJbWYyH0

**Comment by reteo** [comment]
I'm assuming that NoamPeled is the one getting booted?  Are you able to get the client log for NoamPeled as well?

**Comment by gerb82** [comment]
i will try to. currently he needed to go, and i will try it with someone else also

**Comment by reteo** [comment]
Okay.  Just keep in mind that when there are connection issues, it's best to have both sides of the digital conversation... server and client.

**Comment by gerb82** [comment]
server:
http://pastebin.com/8SREpxfs

noampeled's client:
http://paste.feed-the-beast.com/view/465457e6

**Comment by reteo** [comment]
The timeout seems to be happening when JourneyMap starts up on noampeled's side  What happens if JM is disabled?

**Comment by gerb82** [comment]
i will check, but others can connect wich is strange

**Comment by reteo** [comment]
Not necessarily; the problem is likely with the connecting client, not the server.  Which version of Java is the server running?

**Comment by gerb82** [comment]
server, running 8 release 40
his client, 8 release 40/ 8 release 45, i don't remember but i know it's in the log so yea.

the strange thing is that only he can't connect, others can

**Comment by reteo** [comment]
Did you have him check the Java path in the launcher's advanced options?  The log clearly indicated that he was using Java 7 for the game, regardless of the launcher's Java instance.

**Comment by gerb82** [comment]
Well. You can blame it on me because last thing we played was a crash landing challange i created and 1.6.4 usually hates java 8 so we used 7. But let's don't ;)
Thanks anyway.

Between. Hopfully submitting ver 1.1.3 till evning today so we can start the server in this weekend.

**Comment by gerb82** [comment]
I wonder if i should put the java 8 check mod. I know it's a thing but i am not sure how it exacly works. I saw it in a pack called resonant rise on atlauncher and i know that they use it to see if people use versions they know that work

**Comment by reteo** [comment]
Did switching to 8 work?  Or are we still waiting to try it?

**Comment by gerb82** [comment]
workaround by adding the java 8 version check mod
