### ISSUE TITLE
Buildcraft Oil cannot be refined into fuel, needed for the Fuel Enhancer

### ISSUE THREAD

**Issue by reteo** [reteo/Survival-Industry#40]
Buildcraft oil is all over the place, and RotaryCraft can use Buildcraft fuel to make jet fuel.  However, there is no way to make fuel from oil, as the Buildcraft refinery is disabled.

**Comment by reteo** [comment]
At the moment, the easiest solution would be to enable the Buildcraft factory module, since this would also resolve #41.  This would not fit the theme of the modpack, however, as Buildcraft uses Redstone Flux, rather than shaft power, to operate.

For now, the factory module will be re-enabled until a RotaryCraft-compatible refinery and deep pump can be made or found.

**Comment by DriftinFool** [comment]
RoC has en engine that outputs RF from shaft power so you will still need RoC power to run the refinery and pump. So I don't think it really goes against the spirit of the pack. You could always add the rift flux to the quarry recipe like you did with the ender quarry to make it late game only. I think that would keep the balance while allowing the use of BC oil.

**Comment by reteo** [comment]
The quarry is actually part of the Buildcraft build module, and has already been disabled.

I've got to do some work before it appears in the pack; the next version of the pack will have the oil disabled while I work on adding the machines and maintaining the balance.

**Comment by jeffpengMC** [comment]
I'm currently working on a RoC-based Refinery that solves this.

**Comment by reteo** [comment]
The Buildcraft refinery and pump will be added to 1.4.0.
