### ISSUE TITLE
RotaryCraft pump cannot pump liquids more than two blocks below it

### ISSUE THREAD

**Issue by reteo** [reteo/Survival-Industry#41]
The RotaryCraft pump has a 2 block limit to pumping; if the suface of a liquid is further down from the pump than two blocks, then the pump will not continue pumping.  This can be a problem when pumping non-renewable fluids like oil or lava.

**Comment by jeffpengMC** [comment]
I'm currently working on a RoC-based pump that does solve all of these issues. Since Reika mentioned several times he is not willing to change the pumps behavior we'll have to fix this on our end.

**Comment by reteo** [comment]
1.4.0 will use the Buildcraft pump.
