### ISSUE TITLE
Boring machine causes hunger

### ISSUE THREAD

**Issue by jeffpengMC** [reteo/Survival-Industry#44]
Operating the boring machine has some strange interaction with hunger overhaul. It actually "causes" exhaustion and subsequently hunger and eventually starvation just standing next to it.

Since there is a heightened exhaustion penalty for breaking blocks I do assume that HO somehow hooks the block breaking event, links it to the owner of the boring machine, and thus causing hunger.

**Comment by jeffpengMC** [comment]
UPDATE: It's probably not HO but Tool Utilities! While having the a 3x3 pickaxe equipped the bug occours. Also meanwhile the boring machine does not apply mining pipes, blocks are dropped in place and not transferred to the chest.

So it must be TU doing the hook.

**Comment by jeffpengMC** [comment]
There seems to be a maximum distance for this to occur, which is about 4 chunks.

**Comment by reteo** [comment]
Wow... Looks like ToolUtilities is out.  Know of any other non-TiC mod that can supply 3x3 mining without this rather unfortunate side effect?

**Comment by jeffpengMC** [comment]
Nope. I'll have a look about TU. Maybe I can fix this. I really like this mod since it really doesn't do much except just those few things. So I wouldn't wanna lose it.

**Comment by reteo** [comment]
Let me know what you find.  I've found "Torch Tools" which does the right-click placement thing without the need for upgrades (and might just be in line for 1.4), but there's still that 3x3 support that neither of us really want to lose.

**Comment by jeffpengMC** [comment]
It'll be fiddly. Like super. But I think I can do it. I have to teach it [here](https://github.com/wyldmods/ToolUtilities/blob/master/src/main/java/org/wyldmods/toolutilities/common/handlers/AOEHandler.java#L66) that it really does only react to events originating from a *real* player, not by proxy from a player places TileEntity.

While I'm at it... any more wishes? Like 5x5 mining, Autosmelting, Kamehameha on ALT+CTRL+DEL? xD

**Comment by reteo** [comment]
At this point, I have to choose between keeping TU and dropping it.  A fatal bug like this one puts the weight very heavily on the "drop" option, but if you think you can fix it, I'll wait for your word.  If not, let me know so I can let the mod go.

**Comment by jeffpengMC** [comment]
Give me until tomorrow evening. I will relatively quick know if or if not I can do it. Just need to put a lot of logging in and actually *understand* the event object delivered here.

**Comment by reteo** [comment]
No hurry; this decision is for 1.4.

**Comment by jeffpengMC** [comment]
Would be nice to have a fix for 1.3.1 tho.

**Comment by jeffpengMC** [comment]
In this context: 3x1 axe enchantment breaks lumber axes.

**Comment by reteo** [comment]
Hmmm... good point.  Maybe I should disable that feature, then; it's kinda pointless in a game containing lumber axes.  Maybe while I'm at it, I can throw in Torch Tools and disable the right-click placement features of TU as well.  Then, all that's left are the pickaxe upgrades.

**Comment by jeffpengMC** [comment]
Like I said, hold your horses for a day considering the pickaxe thing ;-)

**Comment by jeffpengMC** [comment]
I'm completely at a loss. I cannot reproduce this behavior anymore anywhere, not locally, not on my own server, not even on the SI server anymore. I'll close this for now, please do reopen with as much detail as possible should it reoccur.

**Comment by reteo** [comment]
Huh.  Okay, will do.
