### ISSUE TITLE
ElectriCraft/RotaryCraft Nickel and Platinum won't repair Tinker's Construct Tools

### ISSUE THREAD

**Issue by reteo** [reteo/Survival-Industry#5]
When you try to use ingots of platinum or nickel from ElectriCraft or RotaryCraft (processed by the mod's machines), you find that the tool station/forge won't use it to repair a tool of the same material.

**Comment by reteo** [comment]
Unfortunately, this issue is unlikely to be resolved, as Tinker's Construct is currently being rewritten for 1.8, and all issues for 1.7.10 are being set as "unsupported."    I am currently unable to resolve this issue without assistance from TiC, so at this point, I'm just leaving this issue here for those who want to report it.  I'm aware of it, but I'm powerless to fix it.

**Comment by Dulciphi** [comment]
I'm guessing the mod tweaker method of 
mods.tconstruct.Tweaks.addRepairMaterial(<reika:platinum>, "Platinum", 2); //substitute "reika:platinum" for whatever the correct name is
..doesn't work?

More info [here](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:TConstruct_Support)

**Comment by gerb82** [comment]
There is that mod that can fix it isn't there? You know the one from the forums?

**Comment by reteo** [comment]
The modtweaker command doesn't work; as far as I can tell, Iguana Tinker Tweaks takes over in the repair department.  As for Tinker's Modifiers, I'm not really sure *how* to do that.  There's not a lot of reference to repair materials in the mod, and what there is can likely be referencing the upgrade of a tool, rather than the repair.
