### ISSUE TITLE
Upgrade Reika's Mods to v11

### ISSUE THREAD

**Issue by reteo** [reteo/Survival-Industry#51]
Upgrade to next major version (v11) of Reika's mods:

* DragonAPI
* Expanded Redstone
* RotaryCraft
* ReactorCraft
* ElectriCraft

This is a standard requirement for upgrading the minor version number of the pack.

**Comment by ReikaKalseki** [comment]
Hard to do that when v11 does not exist. :P

**Comment by Rewyn** [comment]
Which is why it's labeled as a milestone. ;)

**Comment by reteo** [comment]
All this "bug" means is that when you release your mods, the next version of Survival Industry will automatically advance one minor version number, since RotaryCraft and friends are a key component of the pack.  1.5.0 is set to happen when v11 of your mods has been released (and stabilized, whatever letter that happens to be).

Oh, and just in case you're curious, the requirement for a major version change would be a change in Minecraft version.
