### ISSUE TITLE
Affine not appearing to show location of Aluminum

### ISSUE THREAD

**Issue by reteo** [reteo/Survival-Industry#6]
When looking for aluminum ore, the ore flower "Affine" is not spawning to show the general areas where it can be found.

**Comment by reteo** [comment]
A new version of Ore Flowers has been released that seems to fix this issue, and will be submitted in the next update to Survival Industry.  The issue will be closed once the resolution is verified.

**Comment by gerb82** [comment]
fixed in 1.1.3
