### ISSUE TITLE
Fatigue management features needed.

### ISSUE THREAD

**Issue by reteo** [reteo/Survival-Industry#60]
Fatigue is an interesting mechanic, but if you sleep and then wake up in the middle of the night with nothing to do, you will be stuck just waiting for something to do.

**Comment by reteo** [comment]
At the moment, Somnia functions under "AND" conditions, meaning that in order to sleep, you have to have minimum fatigue AND you have to be within the enterSleep times.  If this can be changed to use the OR operator, this can mean that fatigue will be a thing, but not at the expense of nighttime sleeping.

I've sent a request to the Somnia mod dev.

**Comment by SvenKayser** [comment]
I suspect there isn't anything from somnia's devs until now, right?

**Comment by reteo** [comment]
He's apparently deciding if he should just go to 1.10, so I'm not going to assume any new versions are coming.

**Comment by reteo** [comment]
Somnia hasn't seen any updates for 1.7.10, so it is no longer installed by default.
