### ISSUE TITLE
Backyard Metalcasting Shouldn't Replace Vanilla Smelting

### ISSUE THREAD

**Issue by reteo** [reteo/Survival-Industry#61]
The Backyard Metalcasting mechanic currently forces a player to use the crucible to smelt ores instead of allowing the vanilla mechanic.  Instead, it would be better to allow the vanilla smelting to happen, and use the Backyard Metalcasting mechanic to provide first-stage ore doubling.

**Comment by jeffpengMC** [comment]
Implemented as of si.core 1.4.1.0
