### ISSUE TITLE
burning recipes. Bibliowoods for Forestry 

### ISSUE THREAD

**Issue by Dulciphi** [reteo/Survival-Industry#65]
All Bibliowoods for Forestry recipes seem to be ..aflame. Instead of requiring Forestry wood planks/slabs, the recipes call for minecraft:fire. I've not yet found where the issue is.. Doesn't seem to be in the scripts. It's not as if the Bibliowoods Forestry items are craftable with fire *and* their usual plank/slab. That's their *only* recipe. It doesn't appear to be only Forestry's Fireproof woods, either - and it's only the Bibliowoods recipes. Forestry fences, etc are fine.

**Comment by jeffpengMC** [comment]
Please hand that over to the mod Authors. That's not on our end.

**Comment by reteo** [comment]
Looks like you can get around the problem by making "framed" versions of the BiblioCraft items, and then applying the desired material in the furniture paneler.  The upside to this is that you can apply _any_ material to the furniture; it doesn't even need to be wood.
