### ISSUE TITLE
Survival Industry 1.4.0 Server Error

### ISSUE THREAD

**Issue by syntax-error** [reteo/Survival-Industry#66]
Mentioned on the FTB thread. (http://forum.feed-the-beast.com/threads/1-7-10-survival-industry-rotarycraft-based-tech.112573/page-33#post-1558119)

Associated Crash Report: http://pastebin.com/xb4AxLmB

**Comment by syntax-error** [comment]
Whoops, sorry. Forgot full log (rather big so its in 3 pastebin parts):

http://pastebin.com/6dpjUqLz
http://pastebin.com/pnha230m
http://pastebin.com/BYVcV8q0

**Comment by jeffpengMC** [comment]
Thanks for the report. This will be fixed fairly shortly.

**Comment by jeffpengMC** [comment]
A potential fix for this is in si.core 1.4.1.0, testing pending.

**Comment by jeffpengMC** [comment]
This issue and several other related have been resolved with si.core 1.4.1.1.

**Comment by reteo** [comment]
NOTE: The new si.core will be released with the next version of Survival Industry.
