### ISSUE TITLE
AT launcher instance - no Apple core?

### ISSUE THREAD

**Issue by AeroyrHwrdd** [reteo/Survival-Industry#67]
So, I load up an instance in the launcher and there is no apple core so I can't play. I understand how I would fix this just wanted to give you a heads up that this is happening.

**Comment by reteo** [comment]
Okay, I enforced the loading of library mods; it should work correctly now.

**Comment by reteo** [comment]
Let me know if there are still issues.  Otherwise, feel free to close this issue.

**Comment by Raganui** [comment]
Just downloaded this pack, getting an applecore error on launch.

**Comment by reteo** [comment]
Can you post the error log.  If pastebin doesn't work, you might want to try Github's "[Gist](https://gist.github.com/)"

**Comment by RainbowDash956** [comment]
Same here. Had to manually install Applecore.

**Comment by reteo** [comment]
AppleCore is now installing correctly.  This issue will be closed.
