### ISSUE TITLE
Forestry back packs not working

### ISSUE THREAD

**Issue by DriftinFool** [reteo/Survival-Industry#69]
The mining pack won't pick up ore and the digger one won't accept cobble/dirt etc. You can't even manually put it in.

**Comment by reteo** [comment]
Any ore at all?  I do know there are issues with ReactorCraft ores (and Reika's already been informed about that), but I'll have to look deeper if it's all ores.

**Comment by DriftinFool** [comment]
Digger's backpack won't accept, sand, dirt, grass, cobblestone, or clay. Miner's backpack won't accept any vanilla, metallurgy, or electricraft/RoC ores.

**Comment by Rewyn** [comment]
Can confirm, also running into this problem with a different pack (still included RotaryCraft etc). Maybe it's a problem on Forestrys side? Though I didn't find anything when I tried to look it up. Didn't pay too much attention to it, as it didn't bother me, so I may have missed something.

**Comment by jeffpengMC** [comment]
Cannot confirm testing with the full pack. Even ReC Ores work for me.

**Comment by jeffpengMC** [comment]
This seems to be related: https://github.com/JasonMcRay/InfiTech-1.7/issues/397

**Comment by Mrjinx453** [comment]
Hi there,
I am running FTB Infinity Evolved on my local machine "Server" and indeed even in single player the bags will not work.
i am running the lastest version!  2.4.1 This is the one running FASTCRAFT.
Honestly im not sure what files you need to check this. I have had a look at the link @jeffpengMC said above but i cant see anything out of place with the "dots" missing in the ore.dic ect
thanks for any help :) My lets play will have to do without the bags for now!

**Comment by reteo** [comment]
At this point, all tests of the Forestry backpack are successful, so the issue will now be closed.
