### ISSUE TITLE
General MO with discontinued mods

### ISSUE THREAD

**Issue by jeffpengMC** [reteo/Survival-Industry#73]
What is our general MO with discontinued mods? Should we really replace them proactively? 

If there is no pending issue with the mod I don't see any need to abandon/replace the mod (Edit: unless there is a superior alternative, ofc). While I welcomed the TiC removal for several other reasons, I wasn't aware of any bug worth kicking it out. As the community slowly starts to move on to 1.8, we will encounter more and more mods that will not update their 1.7.10 variants.

**Comment by reteo** [comment]
Unless there are active issues, I would just place a thread here with the discontinued mod, and keep a passive eye out for replacements for the mod's features.  If there are active issues, then an active eye out would be preferable, unless you plan to maintain those mods yourself.  In that case, of course, you can close the issue. ;)

**Comment by jeffpengMC** [comment]
Well, why I would love to maintain those mods, my time is pretty thin already. If it's a minuscule issue easily fixed we can provide our own fixed version like we did with custom items (if memory serves).

**Comment by reteo** [comment]
Then don't.  Burnout is nothing to be flirting with.
