### ISSUE TITLE
Server Crash on Startup

### ISSUE THREAD

**Issue by RainbowDash956** [reteo/Survival-Industry#75]
The server begins to start up like normal, however it crashes soon after. Here's the crash report.

[crash-2016-01-30_12.49.06-server.txt](https://github.com/reteo/Survival-Industry/files/110914/crash-2016-01-30_12.49.06-server.txt)

**Comment by reteo** [comment]
This issue is a known one, and already being addressed; it will be released with the next version of Survival Industry.  More information is available on #66
