### ISSUE TITLE
Server Missing Libraries (FTB Version)

### ISSUE THREAD

**Issue by RainbowDash956** [reteo/Survival-Industry#76]
When I try to load the FTB launcher's server version, it quits with the message "Forge is missing one or more essential libraries to load."

EDIT: When I manually added in the libraries, it still refused to load, with the message attached.

![error](https://cloud.githubusercontent.com/assets/16859018/12697517/078aba2e-c754-11e5-82ff-5d83e6e1023b.png)

**Comment by reteo** [comment]
Issues with the server will be fixed by the next version; we're double-checking to make sure these and other issues won't block the server from working.

**Comment by RainbowDash956** [comment]
Thanks.

**Comment by jeffpengMC** [comment]
This indicates that log4j is not installed, which you actually need for every forge modded minecraft instance. It is a standard component of the fml libriary package and not related to the server crash described in a different issue.

**Comment by reteo** [comment]
Closing, because the FTB version of the pack is no longer being maintained.
