### ISSUE TITLE
Crash while placing a torch, when another is already present(?)

### ISSUE THREAD

**Issue by Rewyn** [reteo/Survival-Industry#80]
http://pastebin.com/y0Ai4HYQ
Tried placing a torch on the same corner where another one already was, while breaking the first torch. After logging back in, the first torch was gone and the second placed.
The blocks I tried placing it on were just normal wooden planks and smoothstone.
Can't reproduce myself.

**Comment by reteo** [comment]
You can't reproduce it?  Do you mean that it only happened once?

**Comment by Rewyn** [comment]
Yea. JP said something about it a while back already, doesn't look like a regulary thing and not exactly easy to fix.

**Comment by reteo** [comment]
Several versions have passed, and no further word on this issue.  I will assume it's fixed.
