### ISSUE TITLE
OreFlowers: Broadleaf Arrowhead get placed but do not indicate ore

### ISSUE THREAD

**Issue by Cylkin** [reteo/Survival-Industry#86]
Testing 1.5.0 I have Broadleaf Arrowheads being placed everywhere. Since Osmium is disabled by default I guess this is a bug.

**Comment by reteo** [comment]
This is a bug caused by a mod interaction between Nether Ores (which provides the osmium), DragonAPI, and Ore Flowers.  This is a known issue, and it is being looked into.

**Comment by reteo** [comment]
Nether Ores was removed from the pack.  The problem can no longer happen.
