### ISSUE TITLE
Crash when loading part of my world with/without optifine (incase it matters)

### ISSUE THREAD

**Issue by lAimBotl** [reteo/Survival-Industry#87]
[crash-2016-02-22_16.08.15-server.txt](https://github.com/reteo/Survival-Industry/files/141544/crash-2016-02-22_16.08.15-server.txt)

that is with optifine^
without optifine v

[crash-2016-02-22_16.29.49-server.txt](https://github.com/reteo/Survival-Industry/files/141545/crash-2016-02-22_16.29.49-server.txt)

I hope its just me being dumb :|

**Comment by reteo** [comment]
What happens if you don't use FastCraft?

**Comment by lAimBotl** [comment]
[crash-2016-02-22_21.17.35-server.txt](https://github.com/reteo/Survival-Industry/files/141821/crash-2016-02-22_21.17.35-server.txt)

It works with fastcraft without Mo'villages but it doesn't work without fastcraft and with Mo'villages
and it works without both of them.
all of them without optifine

**Comment by reteo** [comment]
Okay, here's what I'm going to have you do.  Go to your "Instances" page in the launcher, and right-click the "Survival Industry" logo for the instance that is crashing.  Select "Share Code."  This will put a share code in the clipboard for pasting.  Then paste it in a response.  That way, I can make a test instance to replicate this issue with your exact build.

**Comment by jeffpengMC** [comment]
I'm pretty sure Mo'Villages messes up here. I don't know where to find the source, so it's hard for me to know what's happening there exactly, but I'd rule out both optifine and fastcraft.

**Comment by reteo** [comment]
Judging from the original thread, I may have been hasty in including Mo'Villages in the pack; the author seems to be too occupied to maintain it, plans to move to 1.8, and doesn't have a source repository.  For now, I'm going to recommend that you do not use Mo'Villages.

**Comment by lAimBotl** [comment]
Sorry my internet went down but I got the code: " kGf6W7Og "

**Comment by reteo** [comment]
Hmmm... I tried that code, and the game started up just fine for me.  Is it possible that something was corrupted during the installation?  Have you tried deleting and reinstalling the instance?

**Comment by lAimBotl** [comment]
same with me but I went exploring in a extreme hills biome and then something loaded and it crashed.

**Comment by reteo** [comment]
Hmmm... when this happened, had you been playing a while?  Was winter coming, or already there?

**Comment by reteo** [comment]
No further information available; it is likely the issue was fixed with subsequent updates of Mo'Villages.
