### ISSUE TITLE
LogisticsPipes has no working crafting recipes

### ISSUE THREAD

**Issue by Cylkin** [reteo/Survival-Industry#89]
The optional mod LogisticsPipes needs BuildCraft robotics for any crafting recipes to be usable (see their [issue #887](https://github.com/RS485/LogisticsPipes/issues/887)).
I tested this, the only recipes that show are for converting pipes.

They seem to be working on getting rid of this dependency, but until then I guess either BC:robotics needs to be included or this mod excluded from the pack.

**Comment by reteo** [comment]
Ug.  I knew I forgot something...

**Comment by reteo** [comment]
Okay, it's been added to the pack, which should update in a couple minutes.
