### ISSUE TITLE
Crash when shift-clicking a recipe for si.core changed recipes

### ISSUE THREAD

**Issue by reteo** [reteo/Survival-Industry#90]
Whenever I attempt to make item with a recipe changed by si.core, (by shift-clicking on NEI's question-mark button while viewing the recipe), the game crashes.  This only seems to happen with recipes that have been altered by si.core; all other recipes seem to work fine.

Included logs:

* http://paste.atlauncher.com/view/239fa193
* http://paste.atlauncher.com/view/89824810

**Comment by jeffpengMC** [comment]
Opposed to initial assumptions this is **not** related to removed recipes.

**Comment by jeffpengMC** [comment]
Apparently this occurs only if non-OreDicted ItemStacks are used in the recipe in question.

**Comment by jeffpengMC** [comment]
Resolved as of https://github.com/reteo/Survival-Industry/commit/07f55eed594d3cc04a230bc649e7a3dc62b15d37
