### ISSUE TITLE
Minecraft Server Crashes running this pack

### ISSUE THREAD

**Issue by PrinceOfIonia** [reteo/Survival-Industry#93]
Hi there! i wanted to play this modpack with my friends! So i downloaded the mods and then dragged them to my forge 1.7.10 server mods folder, i ran the server and this happend

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 3/25/16 2:33 AM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: paulscode/sound/SoundSystemException
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: paulscode/sound/SoundSystemException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 5 more
Caused by: java.lang.ClassNotFoundException: paulscode.sound.SoundSystemException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 29 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 971717872 bytes (926 MB) / 1235746816 bytes (1178 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 1 total; -Xmx3G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 165 mods loaded, 165 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UC	appliedenergistics2-core{rv3-beta-4} [Applied Energistics 2 Core] (minecraft.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UC	OpenComputers|Core{1.5.21.41} [OpenComputers (Core)] (minecraft.jar) 
	UC	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
	UC	si.core.plugin{1.5.0} [Survival Industry FML Loading Plugin] (minecraft.jar) 
	UC	SomniaCore{1.3.1.55} [SomniaCore] (minecraft.jar) 
	UC	OpenModsCore{0.9} [OpenModsCore] (minecraft.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UC	CustomOreGen{1.2.24} [Custom Ore Generation] (CustomOreGen-1.7.10-1.2.24.jar) 
	UC	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UC	HardLib{12.20.0a} [HardLib] (1.7.10-HardLib-12.20.0a.jar) 
	UC	HarderWildlife{12.20.0a} [Harder Wildlife] (1.7.10-HarderWildlife-12.20.0a.jar) 
	UC	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.2.jar) 
	UC	OreFlowers{1.0.0} [Ore Flowers] (1.7.10-OreFlowers-3.0.1c.jar) 
	UC	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UC	StartingInventory{1.7.10.r03} [StartingInventory] ([1.7.10]StartingInventory-universal-1.7.10.r03.jar) 
	UC	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UC	CoFHCore{1.7.10R3.1.0B1} [CoFH Core] (CoFHCore-[1.7.10]3.1.0B1-322.jar) 
	UC	advancedgenetics{1.5.9} [Advanced Genetics] (advancedgenetics-1.7.10-1.5.9.jar) 
	UC	appliedenergistics2{rv3-beta-4} [Applied Energistics 2] (appliedenergistics2-rv3-beta-4.jar) 
	UC	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UC	ae2stuff{0.5.1.61} [AE2 Stuff] (ae2stuff-0.5.1.61-mc1.7.10.jar) 
	UC	AgriCraft{1.7.10-1.4.6-hotfix} [AgriCraft] (AgriCraft-1.7.10-1.4.6-hotfix.jar) 
	UC	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UC	antiqueatlas{1.7.10-4.2.10} [Antique Atlas] (antiqueatlas-1.7.10-4.2.10.jar) 
	UC	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UC	betterstorage{0.13.1.126} [BetterStorage] (BetterStorage-1.7.10-0.13.1.126.jar) 
	UC	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UC	bookshelf{1.0.4.178} [Bookshelf] (Bookshelf-1.7.10-1.0.4.178.jar) 
	UC	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14-core.jar) 
	UC	BuildCraft|Factory{7.1.13} [BC Factory] (buildcraft-7.1.13-factory.jar) 
	UC	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14-builders.jar) 
	UC	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14-energy.jar) 
	UC	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14-robotics.jar) 
	UC	BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14-silicon.jar) 
	UC	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14-transport.jar) 
	UC	Forestry{4.2.1.48} [Forestry for Minecraft] (forestry_1.7.10-4.2.1.48.jar) 
	UC	BuildCraft|Compat{7.1.3} [BuildCraft Compat] (buildcraft-compat-7.1.3.jar) 
	UC	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UC	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UC	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UC	chisel{2.9.4.10} [Chisel] (Chisel-2.9.4.10.jar) 
	UC	climatecontrol{0.4} [Climate Control] (ClimateControl-0.4.beta35.jar) 
	UC	BuildMod{v1.0} [Build Mod] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UC	CoroPets{v1.0} [CoroPets] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UC	CoroAI{v1.0} [CoroAI] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UC	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UC	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UC	craftingtweaks{1.0.62} [Crafting Tweaks] (craftingtweaks-mc1.7.10-1.0.62.jar) 
	UC	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
	UC	D3Core{1.1.0.31} [D3Core] (D3Core-1.7.10-1.1.0.31.jar) 
	UC	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.2.1_1.7.10.jar) 
	UC	props{2.2.1} [Decocraft] (Decocraft-2.2.1_1.7.10.jar) 
	UC	defaultkeys{1.0.24} [Default Keyconfig] (defaultkeys-mc1.7.10-1.0.24.jar) 
	UC	MrTJPCoreMod{1.1.0.32} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.32-universal.jar) 
	UC	ProjRed|Core{4.7.0pre10.93} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre10.93-Base.jar) 
	UC	minechem{5.0.5.406} [Minechem] (Minechem-1.7.10-5.0.5.406.jar) 
	UC	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V10d.jar) 
	UC	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UC	RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V10d.jar) 
	UC	ElectriCraft{1.0} [ElectriCraft] (ElectriCraft 1.7.10 V10b.jar) 
	UC	eplus{4.0.0..73} [Enchanting Plus] (EnchantingPlus-1.7.10-4.0.0.74.jar) 
	UC	endercore{1.7.10-0.2.0.31_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.31_beta.jar) 
	UC	EnderIO{1.7.10-2.3.0.422_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.422_beta.jar) 
	UC	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UC	enderutilities{0.4.4} [Ender Utilities] (enderutilities-1.7.10-0.4.4.jar) 
	UC	enhancedportals{3.0.12} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.12.jar) 
	UC	enviromine{1.3.124} [EnviroMine] (EnviroMine-1.3.124.jar) 
	UC	ExpandedRedstone{1.0} [ExpandedRedstone] (ExpandedRedstone 1.7.10 V10b.jar) 
	UC	extracells{2.3.7} [Extra Cells 2] (ExtraCells-1.7.10-2.3.7b176.jar) 
	UC	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UC	fossil{1.7.10 Build 7.2.1} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.2.1.jar) 
	UC	GardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar) 
	UC	GardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar) 
	UC	GardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar) 
	UC	GardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar) 
	UC	gendustry{1.6.4.134} [GenDustry] (gendustry-1.6.4.134-mc1.7.10.jar) 
	UC	HungerInPeace{1.0.0} [Hunger In Peace] (HungerInPeace-mc1.7.10-1.0.0.jar) 
	UC	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UC	IguanaTweaks{2B} [Iguana Tweaks] (IguanaTweaks-1.7.10-2B.jar) 
	UC	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UC	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UC	mod_Invasion{1.1.5} [Invasion] (Invasion_1.1.5_1.7.10.jar) 
	UC	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UC	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UC	journeymap{5.1.3} [JourneyMap] (journeymap-1.7.10-5.1.3-unlimited.jar) 
	UC	LogisticsPipes{0.9.3.70} [Logistics Pipes] (logisticspipes-0.9.3.70.jar) 
	UC	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UC	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UC	Metallurgy{4.0.8} [Metallurgy 4] (Metallurgy-1.7.10-4.0.8.97.jar) 
	UC	MobProperties{0.4.1} [Mob Properties] (MobProperties-1.7.10-0.4.2.jar) 
	UC	movillages{1.2.1} [Mo' Villages] (MoVillages-1.3.1.jar) 
	UC	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UC	MutantCreatures{1.4.9} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.9.jar) 
	UC	NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) 
	UC	NEIAddons{1.12.15.41} [NEI Addons] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UC	NEIAddons|Developer{1.12.15.41} [NEI Addons: Developer Tools] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UC	NEIAddons|AppEng{1.12.15.41} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UC	NEIAddons|Botany{1.12.15.41} [NEI Addons: Botany] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UC	NEIAddons|Forestry{1.12.15.41} [NEI Addons: Forestry] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UC	NEIAddons|CraftingTables{1.12.15.41} [NEI Addons: Crafting Tables] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UC	NEIAddons|ExNihilo{1.12.15.41} [NEI Addons: Ex Nihilo] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UC	neiintegration{1.1.1} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.1.jar) 
	UC	NetherOres{1.7.10R2.3.1RC1} [Nether Ores] (NetherOres-[1.7.10]2.3.1RC1-19.jar) 
	UC	notenoughkeys{@MOD_VERSION@} [NotEnoughKeys] (NotEnoughKeys-1.7.10-3.0.0b43-universal.jar) 
	UC	OpenMods{0.9} [OpenMods] (OpenModsLib-1.7.10-0.9.jar) 
	UC	OpenBlocks{1.5} [OpenBlocks] (OpenBlocks-1.7.10-1.5.jar) 
	UC	ProjRed|Transmission{4.7.0pre10.93} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre10.93-Integration.jar) 
	UC	OpenComputers{1.5.21.41} [OpenComputers] (OpenComputers-MC1.7.10-1.5.21.41-universal.jar) 
	UC	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UC	weeeflowers{1.7.2b} [Pam's Weee! Flowers] (Pam's WeeeFlowers 1.7.2b.zip) 
	UC	ProjRed|Exploration{4.7.0pre10.93} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre10.93-World.jar) 
	UC	ProjRed|Compatibility{4.7.0pre10.93} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre10.93-Compat.jar) 
	UC	ProjRed|Integration{4.7.0pre10.93} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre10.93-Integration.jar) 
	UC	ProjRed|Illumination{4.7.0pre10.93} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre10.93-Lighting.jar) 
	UC	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UC	ReactorCraft{1.0} [ReactorCraft] (ReactorCraft 1.7.10 V10d.jar) 
	UC	RefinedRelocation{1.1.12} [Refined Relocation] (RefinedRelocation-mc1.7.10-1.1.12.jar) 
	UC	rftools{4.20} [RFTools] (rftools-4.20.jar) 
	UC	Roguelike{1.4.4} [Roguelike Dungeons] (roguelike-1.7.10-1.4.4.jar) 
	UC	RTG{0.4.0} [Realistic Terrain Generation] (RTG-1.7.10-0.4.0.jar) 
	UC	si.core{1.5.0} [Survival Industry] (si.core-1.5.0.jar) 
	UC	si.igniter{1.3.1} [si.igniter] (si.igniter-1.4.0.jar) 
	UC	punt{1.7.10-10.13.0-16.1} [Punt] (smallboats-1.7.10-10.13.0-16.1.jar) 
	UC	whitehall{1.7.10-10.13.0-16.1} [Whitehall] (smallboats-1.7.10-10.13.0-16.1.jar) 
	UC	hoy{1.7.10-10.13.0-16.1} [Hoy] (smallboats-1.7.10-10.13.0-16.1.jar) 
	UC	smallboats{1.7.10-10.13.0-16.1} [SmallBoats (base)] (smallboats-1.7.10-10.13.0-16.1.jar) 
	UC	Somnia{-au} [Somnia] (Somnia-1.4.8.55.jar) 
	UE	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
	UC	SpecialAI{1.1.1} [Special AI] (SpecialAI-1.7.10-1.1.1.jar) 
	UC	SpecialMobs{3.2.1} [Special Mobs] (SpecialMobs-1.7.10-3.2.1.jar) 
	UC	SpiceOfLife{1.3.0} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.3.0.jar) 
	UC	StorageDrawers{1.7.10-1.7.6} [Storage Drawers] (StorageDrawers-1.7.10-1.7.6.jar) 
	UC	StorageDrawersForestry{1.7.10-1.1.1} [Storage Drawers: Forestry Pack] (StorageDrawers-Forestry-1.7.10-1.1.1.jar) 
	UC	Sync{4.0.0} [Sync] (Sync-4.0.0.jar) 
	UC	TerritoryZone{1.0} [TerritoryZone] (TerritoryZone 1.7.10 V10b.jar) 
	UC	ToolUtilities{0.0.1} [Tool Utilities] (ToolUtilities-MC1.7.10-0.0.1-16.jar) 
	UC	TorchTools{1.2.0.27} [TorchTools] (TorchTools-1.7.10-1.2.0.27.jar) 
	UC	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UC	wailaplugins{MC1.7.10-0.2.0-23} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.2.0-23.jar) 
	UC	ZAMod{v1.9.5} [Zombie Awareness] (zombieawareness-1.9.6 for MC v1.7.10.jar) 
	UC	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
	UC	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UC	aobd{2.9.0} [Another One Bites The Dust] (AOBD-2.9.0.jar) 
	UC	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
	UC	VeganOption{0.1.2} [The Vegan Option] (VeganOption-mc1.7.10-0.1.2.jar) 
	UC	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:ENABLED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe
	CoFHCore: -[1.7.10]3.1.0B1-322
	AE2 Version: beta rv3-beta-4 for Forge 10.13.4.1448
	NetherOres: -[1.7.10]2.3.1RC1-19
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

Not Sure What Caused it. I Removed Mo,Villages to see if that was the problem. My friend tried the create server button the one Atlauncher but he said it crashed on startup. I need some help and quick. Thanks!

**Comment by reteo** [comment]
If the above error is from a server installation, then you can place the blame on the shoulders of the "Sound Filters" mod, which is a client-only mod.

Aside from that, however, what error are you getting from the ATLauncher server download?

**Comment by PrinceOfIonia** [comment]
EDIT: i tried the Atlaucher server download, it works fine a guess, it just puts my pc to its knees and have a UNTHINKABLE loading time

**Comment by PrinceOfIonia** [comment]
Thanks By the way!

**Comment by reteo** [comment]
Usually, performance issues are due to a combination of system used to run the server, and the number of mods in the pack; Survival Industry is a very significant modpack by default.  This performance issue was the key reason we made the pack so cconfigurable in the first place.

How much memory is your server using?  How much memory did you assign to the server launcher?

**Comment by reteo** [comment]
Closing due to no further information.  Assuming removal of Sound Filters fixed the problem.
