### ISSUE TITLE
Some block properties missing?

### ISSUE THREAD

**Issue by Xireka** [reteo/Survival-Industry#94]
So, I checked inside the main.js file of si.core yet I can't seem to figure out where the harvest levels for some blocks are changed, most importantly tinker's cobalt and ardite are changed... 

Like it's apparently not there and it set both to cobalt level which is bad since I can't mine them now accordingly to regular progression.

So is si.core changing it or is it another mod? I checked everywhere and I believe si.core is the one doing it.

If someone could answer and help me with that I would be really grateful.

**Comment by reteo** [comment]
Well, first of all, Survival Industry does not use Tinker's Construct (at least, not without manually adding the mod), so there is no cobalt or ardite in that configuration.  

That being said, you can find examples of block properties being changed [here](https://github.com/reteo/Survival-Industry/blob/master/Documents%20and%20Notes/Resource%20Packs/si.core.jmod/main.js#L660); `.br(#)` sets the blast resistance, while `.hl(#)` sets the harvest level of the block.  Where you see `.hl(#,#)`, what you're seeing is the block's meta number and its associated harvest level (for those "multi-ore" block names that separate by meta number).  If you need some ideas what the harvest levels of the tools are, the tool material settings [here](https://github.com/reteo/Survival-Industry/blob/master/Documents%20and%20Notes/Resource%20Packs/si.core.jmod/main.js#L177) can probably give you a clearer picture.

I hope this helps!

**Comment by Xireka** [comment]
That indeed helps a lot thanks.

So quick question to be sure I understand this, Tinker construct Cobalt and Ardite are:
TConstruct:searedbrick:1 and :2, so should the .hl be .hl (#,#) or simply .hl (#)?

According to what you said with multi-ore block names it should be like 
"TConstruct:searedbrick:1 .hl(1,3)" for example, or not? 1 being the :1 and the 3 being the harvest level.

**Comment by reteo** [comment]
It would be something like this:

```
setBlockProperties("TConstruct:searedbrick") .hl(1,3).hl(2,4)
```

1,3 means to set :1 (Cobalt) to harvest level 3, and 2,4 means to set :2 (Ardite) to harvest level 4.

**Comment by Xireka** [comment]
Oh like that, I didn't know I could even put them on the same line like that.

Great, quick and precise answer, thanks a lot. :)

One quick question on the side, last one this time.

What about tool harvest levels? Can I change those too somehow? Like ExtraTic tools or whatever.

**Comment by reteo** [comment]
Before I begin, just a reminder: this configuration is meant for vanilla tools, not Tinker's Construct ones.

If you want to change something about (vanilla) tools, you'd have to alter the tool material.

```
addToolMaterial( "IRON", 4, 250, 6.0,2.0,14, "ingotIron" );
```

This setting affects the iron material, gives it harvest level 4, a durability of 250, a mining speed of 6.0, damage of 2.0, enchantability of 14, and it tells JMOD to allow the tool to be repaired using the ore dictionary entry for iron ingots.

**Comment by Xireka** [comment]
I see, so changing ExtraTiC tools isn't possible this way then?

That's sad but oh well, thanks a lot for the help :)

**Comment by reteo** [comment]
Yeah, sorry.  TiC stopped supporting 1.7.10, so I decided to pull it from this pack as a result.  That's why we went to the trouble to duplicate (non-smeltery) TiC and Iguana's Tinker Tweaks features through this jmod.

**Comment by Xireka** [comment]
It's alright, honestly your jmod is very nicely made and understandable, I only asked on here because I was really stuck, I also found out by sheer luck where to change the different ExtraTiC metal properties so my problem is resolved.

Again, thanks a lot for the fast and precise answers, I learned a few things extra too. :)

Can be closed :)

**Comment by reteo** [comment]
Have fun!
