### ISSUE TITLE
Cant Install Survival Industry

### ISSUE THREAD

**Issue by bambam57** [reteo/Survival-Industry#95]
Every time me or my friends try to install this mod pack using at launcher It says that it didn't install and the check the server log.
http://paste.atlauncher.com/view/99aa85a9

**Comment by AssasinAsha** [comment]
I have this issue as well. Tried every download server in ATL options, nothing works.
Some googling points towards [this forum post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290798-1-6-2-minecraft-sound-improvement-custom-music-a?page=6#c114) with the file. Simply downloading it and putting it in the ATL's Downloads folder seems to do the trick.

**Comment by bambam57** [comment]
Thanks so much that fixed it <3

**Comment by reteo** [comment]
Actually, the issue was simply that the server hosting the file required a secure (https) connection instead of the original http connection.  The URL was changed, and that's what fixed it.

I didn't add it to ATL downloads because I could not find the license that would allow me to do do so.

**Comment by reteo** [comment]
That's odd... I had fixed that issue several days ago; the hosting server msi_conversion.zip was on changed its policy to require a secure (https) connection.  I had corrected that in the installer, and it seems to be working for me.  

The errors in your log point to an SSL certification issue; it's possible that there might be a certificate issue with your copy of Java; reinstalling it might fix that problem.

**Comment by AssasinAsha** [comment]
I probably should have stated that it's a workaround for clients. I did not mean to imply it as an actual, packmaker side fix. Simply that if you're a user and you lack this file, manually putting it into your ATL instance should work.

**Comment by reteo** [comment]
Ah, gotcha.  I'm looking into possible alternatives right now.  I think I might have found something that could supply the needed permission to simply host msi_conversion, and solve the whole problem once and for all.

**Comment by reteo** [comment]
Okay.  Found the line stating that Colonel_Oneill is no longer into modding, and that the pack can be used at will.  It has been hosted, and should now no longer be at the mercy of huricaane's hosting.

**Comment by AssasinAsha** [comment]
Running a super secret military facility, sending people off into space via an ancient and alien artefact, would leave little time for modded Minecraft indeed.

**Comment by reteo** [comment]
Uh huh.  I didn't like the series much; their decision to give a different character the same name from the movie pretty much killed it for me.
