### ISSUE TITLE
CustomOreGen Config Error

### ISSUE THREAD

**Issue by Mummelpuffin** [reteo/Survival-Industry#96]
I'm  trying to set up a server for me and my buddies.  I downloaded through the ATLauncher.  I am using Alternate Terrain Generation.  Here's the error message:

------ Error Message ------

CustomOreGen Config Error at Element <Import> [line 490]: No files found matching 'modules/modpack/Vanilla.xml'.
  in Element <Import> [line 490]
  in Element <Config> [line 33]
  in Document = C:\Users\Colby\Desktop\ATLauncher\Servers\SurvivalIndustry_154\config\CustomOreGen\CustomOreGen_Config.xml

**Comment by reteo** [comment]
Looks like that was an oversight on my part.  If you re-download the server, it should work now.
